X2-11090: Fixed error 'Duplicate payment profile exists for user' when creating a card for an existing user with same existing card
xola/authorizenet pull request #28
Opened 2024-11-12 20:44 UTC by sachinp9797

2024-11-12 21:58 UTC, anush approved these changes

2024-11-13 04:54 UTC, srishaharidas requested changes

2024-11-13 04:54 UTC, srishaharidas commented on src/Message/CIMCreateCardRequest.php
> +            } else {
just do ` } elseif ($response->isSuccessful()) {` here instead? (similar to the block below) that way if you get a non E00039 error you wont enter here.

or for better readability you can do
```
if response succeessful {
   // success logic
} else if ! response succeessful  and error code E00039 {
 // E00039 logic
}

2024-11-13 05:05 UTC, srishaharidas approved these changes

2024-11-13 06:44 UTC, merged